BLUE-154(chore): Enabling Internal Tx search queries
shardeum/explorer-server pull request #20
Opened 2024-07-05 15:51 UTC by achal-singh

Summary
This PR enables querying Internal Tx Types:
> InitNetwork, NodeReward, ChangeConfig, ApplyChangeConfig, SetCertTime, Stake, Unstake, InitRewardTimes, ClaimReward, ChangeNetworkParam, ApplyNetworkParam, Penalty

[**Linear Task - BLUE-154**](https://linear.app/shm/issue/BLUE-154)

2024-07-05 17:36 UTC, jairajdev requested changes

2024-07-05 17:36 UTC, jairajdev commented on src/storage/transaction.ts
> +        const sql = `SELECT * FROM transactions WHERE internalTXType=? AND (txFrom=? OR txTo=? OR nominee=?)`
`ORDER BY cycle DESC, timestamp DESC LIMIT ${limit} OFFSET ${skip}` is missing.

2024-07-05 17:36 UTC, jairajdev commented on src/storage/transaction.ts
> +        transactions = await db.all(sql, [isInternalTxSearchType(txType)[1]])
`ORDER BY cycle DESC, timestamp DESC LIMIT ${limit} OFFSET ${skip}` is missing.

2024-07-06 16:48 UTC, jairajdev approved these changes

2024-07-08 16:30 UTC, merged

2024-08-30 20:56 UTC, mhanson-github commented
In dev